sonar.organization=breehaqasim
sonar.projectKey=breehaqasim_CampusGate-Secure-Admission-Tracker
sonar.projectName=CampusGate Admission Tracker

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.sourceEncoding=UTF-8
